# Generated by Django 6.0.1 on 2026-01-18 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="invoice",
            name="invoice_number",
            field=models.CharField(
                blank=True,
                db_index=True,
                editable=False,
                help_text="Unique identifier for the invoice.",
                max_length=50,
                unique=True,
                verbose_name="invoice number",
            ),
        ),
    ]
