# Generated by Django 6.0.1 on 2026-01-18 09:54

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Amount paid towards the invoice.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="amount",
                    ),
                ),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash"),
                            ("bank_transfer", "Bank Transfer"),
                            ("card", "Credit/Debit Card"),
                            ("mobile_payment", "Mobile Payment"),
                            ("other", "Other"),
                        ],
                        default="bank_transfer",
                        max_length=50,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        help_text="Unique identifier for the payment transaction.",
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="transaction ID",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now,
                        help_text="Date and time when the payment was made.",
                        verbose_name="payment date",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Additional notes or details about the payment.",
                        verbose_name="notes",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="billing.invoice",
                        verbose_name="Invoice",
                    ),
                ),
            ],
            options={
                "verbose_name": "payment",
                "verbose_name_plural": "payments",
                "ordering": ["-paid_at"],
            },
        ),
    ]
