# Generated by Django 6.0.1 on 2026-01-18 09:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(
                        db_index=True,
                        help_text="Name of the product or service.",
                        max_length=255,
                        verbose_name="name",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Detailed description of the product or service.",
                        null=True,
                        verbose_name="description",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="The price per single unit.",
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="price",
                    ),
                ),
                (
                    "track_inventory",
                    models.BooleanField(
                        default=False,
                        help_text="Check this if this is a physical product. Uncheck for services or non-stocked items.",
                        verbose_name="track inventory",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Current stock level. Applicable only if inventory tracking is enabled.",
                        null=True,
                        verbose_name="stock quantity",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this product/service is available for invoicing. Unselect this instead of deleting products to preserve data integrity.",
                        verbose_name="active",
                    ),
                ),
            ],
            options={
                "verbose_name": "product",
                "verbose_name_plural": "products",
                "ordering": ["name"],
            },
        ),
    ]
